### ISSUE TITLE
Can not run under Kivy 2.0.0 (Python 3.9.1)

### ISSUE THREAD

**Issue by yinjilong** [ophermit/xpopup#2]
Thanks for providing this excellent tools,
after upgrading kivy to 2.0.0 under Python 3.9.1,
 running demo_app.py will get the following error.

(garden.xpopup) C:\aaa\working\garden.xpopup>python demo_app.py
[INFO   ] [Logger      ] Record log in C:\Users\aaa\.kivy\logs\kivy_20-12-25_72.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.3.1
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "C:\Users\aaa\.virtualenvs\garden.xpopup-SSj7FHe2\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\aaa\.virtualenvs\garden.xpopup-SSj7FHe2\Scripts\python.exe"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[WARNING] [FileNotFoundError] [Errno 2] No such file or directory: 'C:\\aaa\\working\\garden.xpopup\\xpopup.mo'. Switch to the defaults.
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 - Build 26.20.100.8142'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 630'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 - Build 26.20.100.8142'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
XNotifyBase init kwargs: {'text': 'It could be your Ad', 'title': 'XMessage demo'}
XBase init kwargs: {'text': 'It could be your Ad', 'title': 'XMessage demo'}
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "C:\aaa\working\garden.xpopup\demo_app.py", line 216, in <module>
     runTouchApp(XPopupDemo())
   File "C:\Users\aaa\.virtualenvs\garden.xpopup-SSj7FHe2\lib\site-packages\kivy\base.py", line 582, in runTouchApp
     EventLoop.mainloop()
   File "C:\Users\aaa\.virtualenvs\garden.xpopup-SSj7FHe2\lib\site-packages\kivy\base.py", line 347, in mainloop
     self.idle()
   File "C:\Users\aaa\.virtualenvs\garden.xpopup-SSj7FHe2\lib\site-packages\kivy\base.py", line 391, in idle
     self.dispatch_input()
   File "C:\Users\aaa\.virtualenvs\garden.xpopup-SSj7FHe2\lib\site-packages\kivy\base.py", line 342, in dispatch_input
     post_dispatch_input(*pop(0))
   File "C:\Users\aaa\.virtualenvs\garden.xpopup-SSj7FHe2\lib\site-packages\kivy\base.py", line 308, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\aaa\.virtualenvs\garden.xpopup-SSj7FHe2\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy\_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1132, in kivy._event.EventObservers._dispatch
   File "C:\Users\aaa\.virtualenvs\garden.xpopup-SSj7FHe2\lib\site-packages\kivy\lang\builder.py", line 57, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "<string>", line 14, in <module>
   File "C:\aaa\working\garden.xpopup\demo_app.py", line 91, in _on_click
     XMessage(text='It could be your Ad', title='XMessage demo')
   File "C:\aaa\working\garden.xpopup\notification.py", line 210, in __init__
     super(XNotifyBase, self).__init__(**kwargs)
   File "C:\aaa\working\garden.xpopup\xbase.py", line 125, in __init__
     self.property('buttons').dispatch(self)
   File "kivy\properties.pyx", line 583, in kivy.properties.Property.dispatch
   File "kivy\properties.pyx", line 600, in kivy.properties.Property.dispatch
   File "kivy\_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1154, in kivy._event.EventObservers._dispatch
   File "C:\aaa\working\garden.xpopup\xbase.py", line 152, in on_buttons
     Factory.XButton(
   File "C:\aaa\working\garden.xpopup\tools.py", line 104, in __init__
     super(XLabelBehavior, self).__init__(**defaults)
   File "C:\Users\aaa\.virtualenvs\garden.xpopup-SSj7FHe2\lib\site-packages\kivy\uix\behaviors\button.py", line 121, in __init__
     super(ButtonBehavior, self).__init__(**kwargs)
   File "C:\Users\aaa\.virtualenvs\garden.xpopup-SSj7FHe2\lib\site-packages\kivy\uix\label.py", line 318, in __init__
     super(Label, self).__init__(**kwargs)
   File "C:\Users\aaa\.virtualenvs\garden.xpopup-SSj7FHe2\lib\site-packages\kivy\uix\widget.py", line 350, in __init__
     super(Widget, self).__init__(**kwargs)
   File "kivy\_event.pyx", line 245, in kivy._event.EventDispatcher.__init__
 TypeError: object.__init__() takes exactly one argument (the instance to initialize)

**Comment by tshirtman** [comment]
Were you using python2 before? by the look of the error it might be more about that change than about kivy 2.0.

**Comment by yinjilong** [comment]
I was using python 3.7.9 before without error. 
As the new kivy 2.0 is released(it is said kivy 2.0 can run under python 3.9), I tried to run xpopup  with kivy 2.0+python 3.9.
That gave me the above reported error.
